project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "The Human Cost of Migration in the Americas"
  page-footer:
    left: "rachelmidge@gmail.com"
    right: "This page is built with [Quarto](https://quarto.org/)."
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "The Journey"
        href: journey-risks.qmd
      - text: "Conclusion"
        href: conclusion.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

bibliography: references.bib



